# Generated by Django 5.1.4 on 2025-01-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accountInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('account', models.TextField()),
                ('pw', models.TextField()),
                ('logo', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
    ]
